# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-03-13 13:14:38
"""
import arcpy
from arcpy.sa import *

# To allow overwriting outputs change overwriteOutput option to True.
arcpy.env.overwriteOutput = False

# Check out any necessary licenses.
arcpy.CheckOutExtension("spatial")

Rivers = "Rivers"
towns = "towns"
NLCD_2016_img = arcpy.Raster("NLCD_2016.img")

# Process: Select (Select) (analysis)
Richmond = "C:\\Schoolwork\\NRS_410\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\Richmond"
arcpy.analysis.Select(in_features=towns, out_feature_class=Richmond, where_clause="NAME = 'RICHMOND'")

# Process: Clip (Clip) (analysis)
Rivers_SA = "C:\\Schoolwork\\NRS_410\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\Rivers_SA"
arcpy.analysis.Clip(in_features=Rivers, clip_features=Richmond, out_feature_class=Rivers_SA)

# Process: Buffer (Buffer) (analysis)
Riparian_Zone = "C:\\Schoolwork\\NRS_410\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\Riparian_Zone"
arcpy.analysis.Buffer(in_features=Rivers_SA, out_feature_class=Riparian_Zone, buffer_distance_or_field="100 Meters", dissolve_option="ALL")

# Process: Project Raster (Project Raster) (management)
NLCD_2016_ProjectRaster = "C:\\Schoolwork\\NRS_410\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\NLCD_2016_ProjectRaster"
arcpy.management.ProjectRaster(in_raster=NLCD_2016_img, out_raster=NLCD_2016_ProjectRaster, out_coor_system="PROJCS[\"NAD_1983_StatePlane_Rhode_Island_FIPS_3800_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",328083.3333333333],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Scale_Factor\",0.99999375],PARAMETER[\"Latitude_Of_Origin\",41.08333333333334],UNIT[\"Foot_US\",0.3048006096012192]]", cell_size="100 100")
NLCD_2016_ProjectRaster = arcpy.Raster(NLCD_2016_ProjectRaster)

# Process: Tabulate Area (Tabulate Area) (sa)
Richmond_RI_Riparian_Zones = "C:\\Schoolwork\\NRS_410\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\Richmond_RI_Riparian_Zones"
arcpy.sa.TabulateArea(Riparian_Zone, "OBJECTID", NLCD_2016_ProjectRaster, "NLCD_Land", Richmond_RI_Riparian_Zones, "C:\\Users\\ektic\\OneDrive\\Documents\\ArcGIS\\Projects\\Kelsey_Tichenor_Lab_8\\Kelsey_Tichenor_Lab_8.gdb\\NLCD_2016_ProjectRaster", "CLASSES_AS_ROWS")
.save(Tabulate_Area)
